import Foundation

/// The persisted, engine-independent description of a profile's audio processing.
///
/// This is intentionally separate from `DeviceProfile`: routing and hardware choices
/// belong to the device profile, while this value can later be reused by output,
/// input, and offline processing runtimes.
struct ProcessingProfile: Codable, Hashable, Sendable {
    static let currentSchemaVersion = 7
    static let userPreampStageID = UUID(uuid: (
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 3
    ))
    static let limiterStageID = UUID(uuid: (
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 2
    ))
    static let convolutionStageID = UUID(uuid: (
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 4
    ))
    static let crossfeedStageID = UUID(uuid: (
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 5
    ))

    static func limiterStageID(forChannel index: Int) -> UUID {
        let value = UInt32(clamping: index)
        return UUID(uuid: (
            0x43, 0x41, 0x4d, 0x49, 0x54, 0x55, 0x4e, 0x45,
            0x43, 0x48, 0x00, 0x00,
            UInt8((value >> 24) & 0xff), UInt8((value >> 16) & 0xff),
            UInt8((value >> 8) & 0xff), UInt8(value & 0xff)
        ))
    }

    static func delayStageID(forChannel index: Int) -> UUID {
        let value = UInt32(clamping: index)
        return UUID(uuid: (
            0x43, 0x41, 0x4d, 0x49, 0x54, 0x55, 0x4e, 0x45,
            0x44, 0x4c, 0x00, 0x00,
            UInt8((value >> 24) & 0xff), UInt8((value >> 16) & 0xff),
            UInt8((value >> 8) & 0xff), UInt8(value & 0xff)
        ))
    }

    var schemaVersion: Int
    var global: ProcessingChain
    var channels: [ChannelProcessing]
    /// Non-DSP metadata for a global EQ generated by Device Correction. This
    /// keeps recalculation inputs without reintroducing a correction stage.
    var globalEqualizerProvenance: DeviceCorrectionProfile?

    init(
        schemaVersion: Int = ProcessingProfile.currentSchemaVersion,
        global: ProcessingChain = ProcessingChain(),
        channels: [ChannelProcessing] = ProcessingProfile.stereoChannels,
        globalEqualizerProvenance: DeviceCorrectionProfile? = nil
    ) {
        self.schemaVersion = schemaVersion
        self.global = global
        self.channels = channels
        self.globalEqualizerProvenance = globalEqualizerProvenance
    }

    private enum CodingKeys: String, CodingKey {
        case schemaVersion
        case global
        case channels
        case globalEqualizerProvenance
    }

    init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: CodingKeys.self)
        let storedVersion = try values.decodeIfPresent(Int.self, forKey: .schemaVersion) ?? 1
        guard storedVersion <= Self.currentSchemaVersion else {
            throw DecodingError.dataCorruptedError(
                forKey: .schemaVersion,
                in: values,
                debugDescription: "Unsupported processing schema version \(storedVersion)."
            )
        }
        schemaVersion = Self.currentSchemaVersion
        global = try values.decodeIfPresent(ProcessingChain.self, forKey: .global)
            ?? ProcessingChain()
        global.stages.migrateUserPreampStageID(to: Self.userPreampStageID)
        channels = try values.decodeIfPresent([ChannelProcessing].self, forKey: .channels)
            ?? Self.stereoChannels
        globalEqualizerProvenance = try values.decodeIfPresent(
            DeviceCorrectionProfile.self,
            forKey: .globalEqualizerProvenance
        )
    }

    func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: CodingKeys.self)
        try values.encode(Self.currentSchemaVersion, forKey: .schemaVersion)
        try values.encode(global, forKey: .global)
        try values.encode(channels, forKey: .channels)
        try values.encodeIfPresent(
            globalEqualizerProvenance,
            forKey: .globalEqualizerProvenance
        )
    }

    static var defaultStereo: ProcessingProfile {
        ProcessingProfile().updatingGlobalEqualizer(
            preampDB: 0,
            bands: EQDefaults.bands
        )
    }

    static func imported(from parsed: ParsedEQ) -> ProcessingProfile {
        ProcessingProfile().updatingGlobalEqualizer(
            preampDB: parsed.preampDB,
            bands: parsed.bands
        )
    }

    var globalEqualizer: ParsedEQ {
        let gain = global.stages.userPreampStage(stageID: Self.userPreampStageID)
        let equalizer = global.stages.firstEqualizerStage
        return ParsedEQ(
            preampDB: gain?.isEnabled == true ? gain?.gainDB ?? 0 : 0,
            bands: equalizer?.isEnabled == true ? equalizer?.bands ?? [] : [],
            warnings: []
        )
    }

    var deviceCorrection: DeviceCorrectionProfile? {
        for stage in global.stages {
            if case .deviceCorrection(var correction) = stage.processor {
                correction.isEnabled = stage.isEnabled
                return correction
            }
        }
        return nil
    }

    var limiter: (isEnabled: Bool, processor: LimiterProcessor)? {
        global.stages.firstLimiterStage
    }

    var convolution: (isEnabled: Bool, processor: ConvolutionProcessor)? {
        global.stages.firstConvolutionStage
    }

    var crossfeed: (isEnabled: Bool, processor: CrossfeedProcessor)? {
        global.stages.firstCrossfeedStage
    }

    var limiterEnabled: Bool {
        limiter?.isEnabled ?? false
    }

    /// Presents a legacy Device Correction stage as ordinary editable global EQ.
    /// Biquads and gain stages are linear and can be flattened without changing
    /// their response. New corrections enter the editor in this representation
    /// and are persisted only when the normal EQ Save action is used.
    var globalEqualizerIncludingDeviceCorrection: ParsedEQ {
        var result = globalEqualizer
        guard let correction = deviceCorrection, correction.isEnabled else { return result }
        result.bands.insert(contentsOf: correction.filters, at: 0)
        return result
    }

    mutating func setGlobalEqualizer(preampDB: Double, bands: [EQBand]) {
        global.stages.upsertGain(
            gainDB: preampDB,
            stageID: Self.userPreampStageID
        )
        global.stages.upsertEqualizer(bands: bands)
    }

    mutating func setDeviceCorrection(_ correction: DeviceCorrectionProfile?) {
        let existingIndex = global.stages.firstIndex {
            if case .deviceCorrection = $0.processor { return true }
            return false
        }
        guard var correction else {
            if let existingIndex { global.stages.remove(at: existingIndex) }
            return
        }
        let enabled = correction.isEnabled
        correction.isEnabled = true
        if let existingIndex {
            global.stages[existingIndex].isEnabled = enabled
            global.stages[existingIndex].processor = .deviceCorrection(correction)
        } else {
            global.stages.insert(
                ProcessingStage(
                    isEnabled: enabled,
                    processor: .deviceCorrection(correction)
                ),
                at: 0
            )
        }
    }

    mutating func setLimiterEnabled(_ enabled: Bool) {
        global.stages.upsertLimiter(enabled: enabled, stageID: Self.limiterStageID)
    }

    mutating func setConvolution(
        _ convolution: ConvolutionProcessor?,
        enabled: Bool = true
    ) {
        global.stages.upsertConvolution(
            convolution,
            enabled: enabled,
            stageID: Self.convolutionStageID
        )
    }

    mutating func setCrossfeed(
        _ crossfeed: CrossfeedProcessor?,
        enabled: Bool = true
    ) {
        global.stages.upsertCrossfeed(
            crossfeed,
            enabled: enabled,
            stageID: Self.crossfeedStageID
        )
    }

    func settings(forChannel index: Int) -> ChannelProcessingSettings? {
        guard let channel = channels.first(where: { $0.index == index }) else { return nil }
        return ChannelProcessingSettings(
            gainDB: channel.chain.stages.firstGainStage.flatMap {
                $0.isEnabled ? $0.gainDB : nil
            } ?? 0,
            bands: channel.chain.stages.firstEqualizerStage.flatMap {
                $0.isEnabled ? $0.bands : nil
            } ?? [],
            delayMilliseconds: channel.chain.stages.firstDelayStage.flatMap {
                $0.isEnabled ? $0.processor.milliseconds : nil
            } ?? 0,
            limiterEnabled: channel.chain.stages.firstLimiterStage?.isEnabled ?? false
        )
    }

    mutating func setChannelProcessing(
        index: Int,
        role: ChannelRole,
        gainDB: Double,
        bands: [EQBand],
        delayMilliseconds: Double? = nil,
        limiterEnabled: Bool? = nil
    ) {
        if let channelIndex = channels.firstIndex(where: { $0.index == index }) {
            channels[channelIndex].role = role
            channels[channelIndex].chain.stages.upsertGain(gainDB: gainDB)
            channels[channelIndex].chain.stages.upsertEqualizer(bands: bands)
            if let delayMilliseconds {
                channels[channelIndex].chain.stages.upsertDelay(
                    milliseconds: delayMilliseconds,
                    stageID: Self.delayStageID(forChannel: index)
                )
            }
            if let limiterEnabled {
                channels[channelIndex].chain.stages.upsertLimiter(
                    enabled: limiterEnabled,
                    stageID: Self.limiterStageID(forChannel: index)
                )
            }
        } else {
            var chain = ProcessingChain()
            chain.stages.upsertGain(gainDB: gainDB)
            chain.stages.upsertEqualizer(bands: bands)
            if let delayMilliseconds {
                chain.stages.upsertDelay(
                    milliseconds: delayMilliseconds,
                    stageID: Self.delayStageID(forChannel: index)
                )
            }
            if let limiterEnabled {
                chain.stages.upsertLimiter(
                    enabled: limiterEnabled,
                    stageID: Self.limiterStageID(forChannel: index)
                )
            }
            channels.append(ChannelProcessing(index: index, role: role, chain: chain))
            channels.sort { $0.index < $1.index }
        }
    }

    func updatingGlobalEqualizer(preampDB: Double, bands: [EQBand]) -> ProcessingProfile {
        var copy = self
        copy.setGlobalEqualizer(preampDB: preampDB, bands: bands)
        return copy
    }

    private static let stereoChannels = [
        ChannelProcessing(index: 0, role: .left),
        ChannelProcessing(index: 1, role: .right)
    ]
}

struct ProcessingChain: Codable, Hashable, Sendable {
    var stages: [ProcessingStage]

    init(stages: [ProcessingStage] = []) {
        self.stages = stages
    }
}

struct ChannelProcessing: Identifiable, Codable, Hashable, Sendable {
    var index: Int
    var role: ChannelRole
    var chain: ProcessingChain

    var id: Int { index }

    init(index: Int, role: ChannelRole, chain: ProcessingChain = ProcessingChain()) {
        self.index = index
        self.role = role
        self.chain = chain
    }
}

struct ChannelProcessingSettings: Hashable, Sendable {
    var gainDB: Double
    var bands: [EQBand]
    var delayMilliseconds: Double
    var limiterEnabled: Bool

    static let identity = ChannelProcessingSettings(
        gainDB: 0,
        bands: [],
        delayMilliseconds: 0,
        limiterEnabled: false
    )

    var isIdentity: Bool {
        gainDB == 0 && !bands.contains(where: \.enabled)
            && delayMilliseconds == 0 && !limiterEnabled
    }
}

/// Semantic channel identity is stored separately from the physical channel index.
/// That lets layouts and mixers be changed later without redefining processing data.
enum ChannelRole: String, Codable, Hashable, Sendable, CaseIterable {
    case left
    case right
    case center
    case lowFrequencyEffects
    case leftSurround
    case rightSurround
    case leftRearSurround
    case rightRearSurround
    case unknown
}

struct ProcessingStage: Identifiable, Codable, Hashable, Sendable {
    var id: UUID
    var isEnabled: Bool
    var processor: Processor

    init(id: UUID = UUID(), isEnabled: Bool = true, processor: Processor) {
        self.id = id
        self.isEnabled = isEnabled
        self.processor = processor
    }

    enum Processor: Codable, Hashable, Sendable {
        case gain(GainProcessor)
        case equalizer(EqualizerProcessor)
        case deviceCorrection(DeviceCorrectionProfile)
        case convolution(ConvolutionProcessor)
        case crossfeed(CrossfeedProcessor)
        case delay(DelayProcessor)
        case limiter(LimiterProcessor)

        private enum CodingKeys: String, CodingKey {
            case type
            case gain
            case equalizer
            case deviceCorrection
            case convolution
            case crossfeed
            case delay
            case limiter
        }

        private enum Kind: String, Codable {
            case gain
            case equalizer
            case deviceCorrection
            case convolution
            case crossfeed
            case delay
            case limiter
        }

        init(from decoder: Decoder) throws {
            let values = try decoder.container(keyedBy: CodingKeys.self)
            switch try values.decode(Kind.self, forKey: .type) {
            case .gain:
                self = .gain(try values.decode(GainProcessor.self, forKey: .gain))
            case .equalizer:
                self = .equalizer(try values.decode(EqualizerProcessor.self, forKey: .equalizer))
            case .deviceCorrection:
                self = .deviceCorrection(
                    try values.decode(DeviceCorrectionProfile.self, forKey: .deviceCorrection)
                )
            case .convolution:
                self = .convolution(
                    try values.decode(ConvolutionProcessor.self, forKey: .convolution)
                )
            case .crossfeed:
                self = .crossfeed(
                    try values.decode(CrossfeedProcessor.self, forKey: .crossfeed)
                )
            case .delay:
                self = .delay(try values.decode(DelayProcessor.self, forKey: .delay))
            case .limiter:
                self = .limiter(try values.decode(LimiterProcessor.self, forKey: .limiter))
            }
        }

        func encode(to encoder: Encoder) throws {
            var values = encoder.container(keyedBy: CodingKeys.self)
            switch self {
            case .gain(let processor):
                try values.encode(Kind.gain, forKey: .type)
                try values.encode(processor, forKey: .gain)
            case .equalizer(let processor):
                try values.encode(Kind.equalizer, forKey: .type)
                try values.encode(processor, forKey: .equalizer)
            case .deviceCorrection(let correction):
                try values.encode(Kind.deviceCorrection, forKey: .type)
                try values.encode(correction, forKey: .deviceCorrection)
            case .convolution(let processor):
                try values.encode(Kind.convolution, forKey: .type)
                try values.encode(processor, forKey: .convolution)
            case .crossfeed(let processor):
                try values.encode(Kind.crossfeed, forKey: .type)
                try values.encode(processor, forKey: .crossfeed)
            case .delay(let processor):
                try values.encode(Kind.delay, forKey: .type)
                try values.encode(processor, forKey: .delay)
            case .limiter(let processor):
                try values.encode(Kind.limiter, forKey: .type)
                try values.encode(processor, forKey: .limiter)
            }
        }
    }
}

struct GainProcessor: Codable, Hashable, Sendable {
    var gainDB: Double
}

struct EqualizerProcessor: Codable, Hashable, Sendable {
    var bands: [EQBand]
}

struct ConvolutionProcessor: Codable, Hashable, Sendable {
    var asset: ImpulseResponseAsset
    /// Zero-based channel selected from a mono or multichannel WAV.
    var impulseChannel: Int

    init(asset: ImpulseResponseAsset, impulseChannel: Int = 0) {
        self.asset = asset
        self.impulseChannel = impulseChannel
    }
}

struct CrossfeedProcessor: Codable, Hashable, Sendable {
    static let standard = CrossfeedProcessor(
        amountPercent: 25,
        delayMilliseconds: 0.3,
        cutoffFrequency: 700
    )

    /// Opposite-channel low-frequency contribution, from 0% (none) to 100%
    /// (equal-amplitude low-frequency contribution).
    var amountPercent: Double
    var delayMilliseconds: Double
    var cutoffFrequency: Double

    var crossfeedCoefficient: Double { amountPercent / 100 }

    var crossfeedGainDB: Double {
        let coefficient = crossfeedCoefficient
        guard coefficient > 0 else { return -120 }
        return 20 * log10(coefficient)
    }

    var maximumBoostDB: Double {
        20 * log10(1 + max(0, crossfeedCoefficient))
    }
}

struct DelayProcessor: Codable, Hashable, Sendable {
    var milliseconds: Double
}

struct LimiterProcessor: Codable, Hashable, Sendable {
    static let standard = LimiterProcessor(clipLimitDB: -0.5, softClip: false)

    var clipLimitDB: Double
    var softClip: Bool
}

private extension Array where Element == ProcessingStage {
    var firstGainStage: (isEnabled: Bool, gainDB: Double)? {
        for stage in self {
            if case .gain(let gain) = stage.processor {
                return (stage.isEnabled, gain.gainDB)
            }
        }
        return nil
    }

    var firstEqualizerStage: (isEnabled: Bool, bands: [EQBand])? {
        for stage in self {
            if case .equalizer(let equalizer) = stage.processor {
                return (stage.isEnabled, equalizer.bands)
            }
        }
        return nil
    }

    var firstLimiterStage: (isEnabled: Bool, processor: LimiterProcessor)? {
        for stage in self {
            if case .limiter(let limiter) = stage.processor {
                return (stage.isEnabled, limiter)
            }
        }
        return nil
    }

    var firstConvolutionStage: (isEnabled: Bool, processor: ConvolutionProcessor)? {
        for stage in self {
            if case .convolution(let convolution) = stage.processor {
                return (stage.isEnabled, convolution)
            }
        }
        return nil
    }

    var firstCrossfeedStage: (isEnabled: Bool, processor: CrossfeedProcessor)? {
        for stage in self {
            if case .crossfeed(let crossfeed) = stage.processor {
                return (stage.isEnabled, crossfeed)
            }
        }
        return nil
    }

    var firstDelayStage: (isEnabled: Bool, processor: DelayProcessor)? {
        for stage in self {
            if case .delay(let delay) = stage.processor {
                return (stage.isEnabled, delay)
            }
        }
        return nil
    }

    func userPreampStage(stageID: UUID) -> (isEnabled: Bool, gainDB: Double)? {
        if let stage = first(where: { $0.id == stageID }),
           case .gain(let gain) = stage.processor {
            return (stage.isEnabled, gain.gainDB)
        }
        return firstGainStage
    }

    mutating func migrateUserPreampStageID(to stageID: UUID) {
        if let reservedIndex = firstIndex(where: { $0.id == stageID }) {
            if case .gain = self[reservedIndex].processor { return }
            // A malformed/hand-authored profile may already use the reserved
            // ID for another stage. Preserve that stage under a fresh identity
            // before assigning the semantic User-preamp identity.
            self[reservedIndex].id = UUID()
        }
        guard let legacyGainIndex = firstIndex(where: {
            if case .gain = $0.processor { return true }
            return false
        }) else { return }
        self[legacyGainIndex].id = stageID
    }

    mutating func upsertGain(gainDB: Double, stageID: UUID? = nil) {
        let index: Int?
        if let stageID {
            index = firstIndex(where: { stage in
                guard stage.id == stageID else { return false }
                if case .gain = stage.processor { return true }
                return false
            })
        } else {
            index = firstIndex(where: {
                if case .gain = $0.processor { return true }
                return false
            })
        }
        if let index {
            self[index].processor = .gain(GainProcessor(gainDB: gainDB))
            self[index].isEnabled = true
        } else {
            insert(ProcessingStage(
                id: stageID ?? UUID(),
                processor: .gain(GainProcessor(gainDB: gainDB))
            ), at: 0)
        }
    }

    mutating func upsertEqualizer(bands: [EQBand]) {
        if let index = firstIndex(where: {
            if case .equalizer = $0.processor { return true }
            return false
        }) {
            self[index].processor = .equalizer(EqualizerProcessor(bands: bands))
            self[index].isEnabled = true
        } else {
            append(ProcessingStage(processor: .equalizer(EqualizerProcessor(bands: bands))))
        }
    }

    mutating func upsertLimiter(enabled: Bool, stageID: UUID) {
        if let index = firstIndex(where: {
            if case .limiter = $0.processor { return true }
            return false
        }) {
            self[index].isEnabled = enabled
        } else {
            append(ProcessingStage(
                id: stageID,
                isEnabled: enabled,
                processor: .limiter(.standard)
            ))
        }
    }

    mutating func upsertDelay(milliseconds: Double, stageID: UUID) {
        if let index = firstIndex(where: {
            if case .delay = $0.processor { return true }
            return false
        }) {
            self[index].processor = .delay(DelayProcessor(milliseconds: milliseconds))
            self[index].isEnabled = true
            return
        }
        let insertionIndex = firstIndex(where: {
            if case .limiter = $0.processor { return true }
            return false
        }) ?? endIndex
        insert(
            ProcessingStage(
                id: stageID,
                processor: .delay(DelayProcessor(milliseconds: milliseconds))
            ),
            at: insertionIndex
        )
    }

    mutating func upsertConvolution(
        _ convolution: ConvolutionProcessor?,
        enabled: Bool,
        stageID: UUID
    ) {
        let index = firstIndex(where: {
            if case .convolution = $0.processor { return true }
            return false
        })
        guard let convolution else {
            if let index { remove(at: index) }
            return
        }
        if let index {
            self[index].processor = .convolution(convolution)
            self[index].isEnabled = enabled
            return
        }

        // FIR follows ordinary response shaping and remains before the terminal
        // limiter even when an older profile's stages were hand-authored.
        let insertionIndex = firstIndex(where: {
            switch $0.processor {
            case .crossfeed, .limiter: return true
            default: return false
            }
        }) ?? endIndex
        insert(
            ProcessingStage(
                id: stageID,
                isEnabled: enabled,
                processor: .convolution(convolution)
            ),
            at: insertionIndex
        )
    }


    mutating func upsertCrossfeed(
        _ crossfeed: CrossfeedProcessor?,
        enabled: Bool,
        stageID: UUID
    ) {
        let index = firstIndex(where: {
            if case .crossfeed = $0.processor { return true }
            return false
        })
        guard let crossfeed else {
            if let index { remove(at: index) }
            return
        }
        if let index {
            self[index].processor = .crossfeed(crossfeed)
            self[index].isEnabled = enabled
            return
        }
        let insertionIndex = firstIndex(where: {
            if case .limiter = $0.processor { return true }
            return false
        }) ?? endIndex
        insert(
            ProcessingStage(
                id: stageID,
                isEnabled: enabled,
                processor: .crossfeed(crossfeed)
            ),
            at: insertionIndex
        )
    }
}

enum EQDefaults {
    static let bands = [
        EQBand(kind: .lowShelf, frequency: 31, gain: 0, q: 1),
        EQBand(kind: .peaking, frequency: 76, gain: 0, q: 1),
        EQBand(kind: .peaking, frequency: 184, gain: 0, q: 1),
        EQBand(kind: .peaking, frequency: 447, gain: 0, q: 1),
        EQBand(kind: .peaking, frequency: 1_087, gain: 0, q: 1),
        EQBand(kind: .peaking, frequency: 2_643, gain: 0, q: 1),
        EQBand(kind: .peaking, frequency: 6_423, gain: 0, q: 1),
        EQBand(kind: .highShelf, frequency: 16_000, gain: 0, q: 1)
    ]
}

struct EqualizerAPOSerializer {
    func serialize(_ parsed: ParsedEQ) -> String {
        var lines = ["Preamp: \(format(parsed.preampDB)) dB"]
        for (index, band) in parsed.bands.enumerated() {
            let state = band.enabled ? "ON" : "OFF"
            var line = "Filter \(index + 1): \(state) \(token(band.kind))"
            line += " Fc \(format(max(1, band.frequency))) Hz"
            if usesGain(band.kind) { line += " Gain \(format(band.gain ?? 0)) dB" }
            line += " Q \(format(max(0.05, band.q ?? 0.70710678)))"
            lines.append(line)
        }
        return lines.joined(separator: "\n")
    }

    private func usesGain(_ kind: EQBand.Kind) -> Bool {
        kind == .peaking || kind == .lowShelf || kind == .highShelf
    }

    private func token(_ kind: EQBand.Kind) -> String {
        switch kind {
        case .peaking: return "PK"
        case .lowShelf: return "LS"
        case .highShelf: return "HS"
        case .lowPass: return "LPQ"
        case .highPass: return "HPQ"
        case .notch: return "NO"
        case .allPass: return "AP"
        }
    }

    private func format(_ value: Double) -> String {
        String(format: "%.8g", locale: Locale(identifier: "en_US_POSIX"), value)
    }
}
